"""
Shared Database Models - Universal Schema with Market Isolation

All models include 'market' column to ensure complete isolation between:
- ASX (Australia)
- USA (United States)
- TWN (Taiwan)

CRITICAL: Always use query helpers (.for_market()) to prevent cross-market data leaks.
"""

from sqlalchemy import UniqueConstraint
from sqlalchemy.dialects.postgresql import ARRAY
from app.bot import db
from datetime import datetime


class MarketIsolatedModel:
    """Base class for market-isolated models with query helpers"""
    
    @classmethod
    def for_market(cls, market):
        """
        Query helper to enforce market filtering
        
        Usage:
            Signal.for_market('ASX').all()
            ConfigProfile.for_market('USA').filter_by(name='Growth').first()
        """
        return cls.query.filter_by(market=market)
    
    @classmethod
    def get_markets(cls):
        """Get list of all markets in database"""
        return db.session.query(cls.market).distinct().all()


class Signal(MarketIsolatedModel, db.Model):
    """
    Trading signals generated by AI consensus
    
    Market Isolation: Each market has separate signals (ASX signals never mix with USA)
    Idempotency: UniqueConstraint prevents duplicate signals for same date/ticker/market
    """
    __tablename__ = 'signals'
    
    id = db.Column(db.Integer, primary_key=True)
    market = db.Column(db.String(10), nullable=False, index=True)
    date = db.Column(db.Date, nullable=False, default=datetime.utcnow().date)
    ticker = db.Column(db.String(20), nullable=False)
    signal = db.Column(db.String(10), nullable=False)  # BUY, SELL, HOLD
    confidence = db.Column(db.Float, nullable=False)
    job_type = db.Column(db.String(50), default='daily-signal')
    trigger_type = db.Column(db.String(20), default='scheduled')
    sent_at = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        UniqueConstraint('market', 'date', 'ticker', 'job_type', name='uq_signal_market_date'),
        {'comment': 'AI-generated trading signals with market isolation'}
    )
    
    def __repr__(self):
        return f"<Signal {self.market}:{self.ticker} {self.signal} {self.date}>"


class ConfigProfile(MarketIsolatedModel, db.Model):
    """
    Trading strategy profiles (isolated per market)
    
    Market Isolation: ASX profiles cannot access USA stocks and vice versa
    Each market has independent profile names (e.g., ASX 'Growth' != USA 'Growth')
    """
    __tablename__ = 'config_profiles'
    
    id = db.Column(db.Integer, primary_key=True)
    market = db.Column(db.String(10), nullable=False, index=True)
    name = db.Column(db.String(255), nullable=False)
    stocks = db.Column(ARRAY(db.String), nullable=False)
    holding_period = db.Column(db.Integer, nullable=False, default=30)
    hurdle_rate = db.Column(db.Float, nullable=False, default=0.05)
    max_position_size = db.Column(db.Float, nullable=False, default=10000.0)
    stop_loss = db.Column(db.Float, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    __table_args__ = (
        UniqueConstraint('market', 'name', name='uq_profile_market_name'),
        {'comment': 'Trading strategy profiles with market isolation'}
    )
    
    def __repr__(self):
        return f"<ConfigProfile {self.market}:{self.name} ({len(self.stocks)} stocks)>"


class ApiCredential(db.Model):
    """
    Encrypted API credentials for notifications (shared across markets)
    
    Note: No market column - credentials like Telegram token are universal
    """
    __tablename__ = 'api_credentials'
    
    id = db.Column(db.Integer, primary_key=True)
    service_name = db.Column(db.String(100), nullable=False, unique=True)
    encrypted_value = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def __repr__(self):
        return f"<ApiCredential {self.service_name}>"


class JobLog(MarketIsolatedModel, db.Model):
    """
    Job execution logs (isolated per market for debugging)
    
    Market Isolation: ASX job failures don't affect USA/TWN logs
    """
    __tablename__ = 'job_logs'
    
    id = db.Column(db.Integer, primary_key=True)
    market = db.Column(db.String(10), nullable=False, index=True)
    job_type = db.Column(db.String(50), nullable=False)
    status = db.Column(db.String(20), nullable=False)  # success, failure
    duration_seconds = db.Column(db.Float, nullable=True)
    error_message = db.Column(db.Text, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    
    def __repr__(self):
        return f"<JobLog {self.market}:{self.job_type} {self.status}>"
